import 'package:flutter/cupertino.dart';
import 'package:zero_grau/models/products_model.dart';

final filterListAlcoholic = [
  'Brahma',
  'Heineken',
  'Stella',
  'Einsenbahn',
  'Vinho',
  'Destilados',
];

final filterListNoAlcoholic = [
  'Refrigerante',
  'Suco',
  'Energético',
  'Água',
];

List<ProductsModel> productsItems = [
  ProductsModel(
    id: '1',
    name: 'Heineken',
    price: '6.99',
    image: 'assets/images/heineken_350.png',
    description: 'Cerveja Heineken 350ml',
    category: 'cerveja',
    brand: 'Heineken',
    unit: 'un',
    size: '350ml',
    alcoolic: true,
  ),
  ProductsModel(
    id: '2',
    name: 'Einsenbahn',
    price: '5.99',
    image: 'assets/images/eisenbahn_350.png',
    description: 'Cerveja Einsenbahn 350ml',
    category: 'cerveja',
    brand: 'Einsenbahn',
    unit: 'un',
    size: '350ml',
    alcoolic: true,
  ),
  ProductsModel(
    id: '3',
    name: 'Bohemia',
    price: '4.99',
    image: 'assets/images/bohemia_350.jpg',
    description: 'Cerveja Bohemia 350ml',
    category: 'cerveja',
    brand: 'Bohemia',
    unit: 'un',
    size: '350ml',
    alcoolic: true,
  ),
  ProductsModel(
    id: '4',
    name: 'Stella',
    price: '5.99',
    image: 'assets/images/stella_350.jpg',
    description: 'Cerveja Stella 350ml',
    category: 'cerveja',
    brand: 'Stella',
    unit: 'un',
    size: '350ml',
    alcoolic: true,
  ),
  ProductsModel(
    id: '5',
    name: 'Aguá mineral Minalba',
    price: '1,99',
    image: 'assets/images/minalba_500ml.jpg',
    description: 'Agua mineral Minalba 500ml',
    category: 'agua',
    brand: 'Minalba',
    unit: 'un',
    size: '500ml',
    alcoolic: false,
  ),
  ProductsModel(
    id: '6',
    name: 'Coca-Cola',
    price: '7,99',
    image: 'assets/images/cocaCola_2l.jpeg',
    description: 'Cola-Cola 2L',
    category: 'refrigerante',
    brand: 'Coca-Cola',
    unit: 'un',
    size: '2L',
    alcoolic: false,
  ),
  ProductsModel(
    id: '7',
    name: 'Coca-Cola',
    price: '2.99',
    image: 'assets/images/cocaCola_350ml.png',
    description: 'Coca-Cola Lata 350ml',
    category: 'refrigerante',
    brand: 'Coca-Cola',
    unit: 'un',
    size: '350ml',
    alcoolic: false,
  ),
  ProductsModel(
    id: '8',
    name: 'RedBull',
    price: '8.99',
    image: 'assets/images/redBull_250ml.jpg',
    description: 'Red Bull 250ml',
    category: 'cerveja',
    brand: 'Red Bull',
    unit: 'un',
    size: '250ml',
    alcoolic: false,
  )
];
